rootProject.name = "KUpdater"

include("api")
include("core")
include("platform:common")
include("platform:v1_8")
include("platform:v1_13")
include("platform:v1_21")
include("features:tools")
include("features:progression")
include("features:combat")
include("features:farming")
include("features:mining")
include("features:economy")
include("features:exploration")
include("bootstrap")
include("testing")
